/*
 * File: app/store/CategoryItems.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BucketList.store.CategoryItems', {
    extend: 'Ext.data.Store',

    config: {
        pageSize: 10,
        storeId: 'CategoryItems',
        proxy: {
            type: 'ajax',
            url: 'http://localhost:3000/bc/bucketcategory',
            reader: {
                type: 'json',
                rootProperty: 'data'
            }
        },
        fields: [
            {
                name: 'id',
                type: 'int'
            },
            {
                name: 'text'
            },
            {
                name: 'category'
            }
        ]
    }
});