/*
 * File: app/store/CategoryChart.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BucketList.store.CategoryChart', {
    extend: 'Ext.data.Store',

    config: {
        storeId: 'CategoryChart',
        proxy: {
            type: 'ajax',
            url: 'http://api.bc7.us/bc/categorycount',
            reader: {
                type: 'json',
                rootProperty: 'data'
            }
        },
        fields: [
            {
                name: 'category'
            },
            {
                name: 'thecount',
                type: 'int'
            }
        ]
    }
});