/*
 * File: app/view/CategoryPie.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BucketList.view.CategoryPie', {
    extend: 'Ext.chart.PolarChart',
    alias: 'widget.categorypie1',

    config: {
        store: 'CategoryChart',
        colors: [
            '#115fa6',
            '#94ae0a',
            '#a61120',
            '#ff8809',
            '#ffd13e',
            '#a61187',
            '#24ad9a',
            '#7c7474',
            '#a66111'
        ],
        series: [
            {
                type: 'pie',
                labelField: 'category',
                xField: 'thecount',
                donut: 20
            }
        ],
        interactions: [
            {
                type: 'rotate'
            }
        ]
    }

});