/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BucketList.view.Main', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.main',

    requires: [
        'BucketList.view.MyItems',
        'BucketList.view.Categories',
        'BucketList.view.CategoryPie',
        'BucketList.view.CategoryBar',
        'BucketList.view.Login'
    ],

    config: {
        items: [
            {
                xtype: 'myitems',
                title: 'My Items',
                iconCls: 'star'
            },
            {
                xtype: 'categories',
                title: 'Categories',
                iconCls: 'organize'
            },
            {
                xtype: 'carousel',
                title: 'Charts',
                iconCls: 'download',
                itemId: 'mycarousel',
                items: [
                    {
                        xtype: 'categorypie1'
                    },
                    {
                        xtype: 'categorybar'
                    },
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        title: 'Charts'
                    }
                ]
            },
            {
                xtype: 'login',
                title: 'Login',
                iconCls: 'user'
            }
        ],
        tabBar: {
            docked: 'bottom'
        },
        listeners: [
            {
                fn: 'onMycarouselShow',
                event: 'show',
                delegate: '#mycarousel'
            }
        ]
    },

    onMycarouselShow: function(component, eOpts) {
        Ext.getStore('CategoryChart').load();
    }

});