/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BucketList.view.Main', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.main',

    config: {
        items: [
            {
                xtype: 'container',
                title: 'My Items',
                iconCls: 'star'
            },
            {
                xtype: 'container',
                title: 'Categories',
                iconCls: 'organize'
            },
            {
                xtype: 'container',
                title: 'Login',
                iconCls: 'user'
            },
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'My Bucket List'
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});