/*
 * File: app/controller/Login.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BucketList.controller.Login', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "button#login": {
                tap: 'loginButtonTap'
            },
            "button#createaccount": {
                tap: 'createButtonTap'
            }
        }
    },

    loginButtonTap: function(button, e, eOpts) {
        BucketList.util.Bootcamp.loginSubmit( button);
    },

    createButtonTap: function(button, e, eOpts) {
        BucketList.util.Bootcamp.createAccountSubmit( button);
    }

});