/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BucketList.controller.Main', {
    extend: 'Ext.app.Controller',

    config: {
        views: [
            'MyItems'
        ],

        control: {
            "list#myitems": {
                show: 'onMylist1Show',
                itemswipe: 'onMylist1ItemSwipe'
            }
        }
    },

    onMylist1Show: function(component, eOpts) {
        BucketList.util.Bootcamp.showMyItems();
    },

    onMylist1ItemSwipe: function(dataview, index, target, record, e, eOpts) {
        BucketList.util.Bootcamp.removeBucketItem( record);
    }

});